AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The backend of my portfolio
Resources:
  portfolioBackend:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.app
      Runtime: nodejs12.x
      CodeUri: s3://lambda-deployment-artifacts-portfolio-backend/b6b3fc02faa36f650818ea963975122b
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /
            Method: get
Outputs:
  portfolioBackendApi:
    Description: API Gateway endpoint URL for Prod stage for backend
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.sa-east-1.amazonaws.com/Prod/
  portfolioBackend:
    Description: Backend Lambda Function
    Value:
      Fn::GetAtt:
      - portfolioBackend
      - Arn
