service: backendPortfolio
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1
functions:
  app:
    handler: index.server
    events:
      - http:
          path: /
          method: GET
          cors: true
      - http:
          path: /signup
          method: POST
          cors: true
      - http:
          path: /signin
          method: POST
          cors: true
      - http:
          path: /authorize
          method: GET
          cors: true
      - http:
          path: /saveContact
          method: POST
          cors: true
      - http:
          path: /getContacts
          method: GET
          cors: true
useDotenv: true